# Generated by Django 4.2.26 on 2025-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_jobtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={},
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
