# Generated by Django 4.2.26 on 2025-11-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_alter_job_options_alter_jobcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs_app.jobtype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='offered_salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-solid fa-laptop)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
