# Generated by Django 4.2.26 on 2025-11-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0006_alter_jobcategory_options_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': 'Job Types'},
        ),
    ]
