# Generated by Django 4.2.26 on 2025-11-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_companyprofile_about_companyprofile_address_and_more'),
        ('jobs_app', '0007_alter_jobtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies_app.companyprofile'),
        ),
    ]
