# Generated by Django 4.2.26 on 2025-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='offered_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Job requirements', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Job responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. 30000-40000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Required skills', null=True),
        ),
    ]
