# Generated by Django 4.2.26 on 2025-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_remove_job_offered_salary_job_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Onsite', help_text='Mode of work', max_length=20),
        ),
    ]
