# Generated by Django 5.2.8 on 2025-11-24 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0003_companyprofile_pinterest_companyprofile_tumblr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed about section', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full physical address', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Google Maps Embed Iframe Code', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='General company responsibilities or culture', null=True),
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_title', models.CharField(max_length=200)),
                ('review_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies_app.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Review',
                'verbose_name_plural': 'Company Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
