# Generated by Django 4.2.26 on 2025-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_companyprofile_about_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Top Companies',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
