# Generated by Django 4.2.26 on 2025-11-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Extended', 'Extended')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.CharField(default='Monthly', max_length=20)),
                ('features', models.JSONField()),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('online_profile', 'Online Profile'), ('work_sample', 'Work Sample'), ('research', 'Research / Publication'), ('presentation', 'Presentation'), ('certification', 'Certification'), ('patent', 'Patent')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('application_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
