# Generated by Django 4.2.7 on 2025-11-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Extended', 'Extended')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.CharField(default='Monthly', max_length=20)),
                ('features', models.JSONField()),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
