# Generated by Django 4.2.7 on 2025-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('mode_of_payment', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=20)),
                ('uan_no', models.CharField(max_length=20)),
                ('esic_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
