# Generated by Django 4.2.7 on 2025-11-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyPhoto',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
