# Generated by Django 4.2.7 on 2025-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
