# Generated by Django 4.2.7 on 2025-11-26 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0003_candidateproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredCareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('functional_area', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contractual', 'Contractual')], max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, null=True)),
                ('preferred_shift', models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night'), ('Part Time', 'Part Time')], max_length=50, null=True)),
                ('availability_to_join', models.DateField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, choices=[('USD', 'US Dollars'), ('INR', 'Indian Rupees')], max_length=20, null=True)),
                ('salary_lakh', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_thousand', models.CharField(blank=True, max_length=20, null=True)),
                ('desired_location', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desired_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
