# Generated by Django 4.2.7 on 2025-11-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_menu_submenu_menupermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='panel_type',
        ),
    ]
