# Generated by Django 4.2.7 on 2025-11-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksample',
            name='user',
        ),
        migrations.DeleteModel(
            name='OnlineProfile',
        ),
        migrations.DeleteModel(
            name='WorkSample',
        ),
    ]
