# Generated by Django 4.2.7 on 2025-11-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_menu_panel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms & Conditions', max_length=255)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='admin_app.termsandconditions')),
            ],
        ),
        migrations.CreateModel(
            name='TermsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('bullet', 'Bullet Point'), ('subheading', 'Sub Heading')], default='paragraph', max_length=20)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='admin_app.termssection')),
            ],
        ),
    ]
