# Generated by Django 4.2.7 on 2025-11-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0004_remove_worksample_user_delete_onlineprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('online_profile', 'Online Profile'), ('work_sample', 'Work Sample'), ('research', 'Research / Publication'), ('presentation', 'Presentation'), ('certification', 'Certification'), ('patent', 'Patent')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('application_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
