# Generated by Django 4.2.7 on 2025-11-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_department_employee_designation'),
        ('admin_app', '0005_department_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
