# Generated by Django 4.2.7 on 2025-11-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateAdditionalDetail',
        ),
    ]
