# Generated by Django 4.2.7 on 2025-11-25 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0010_candidateemployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Graduation/Diploma', 'Graduation/Diploma'), ('Masters/Post-Graduation', 'Masters/Post-Graduation'), ('PhD/Doctorate', 'PhD/Doctorate')], max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
