# Generated by Django 4.2.7 on 2025-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='post_code',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='tumblr',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='youtube',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='job_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
