# Generated by Django 4.2.7 on 2025-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name': 'Candidate Profile', 'verbose_name_plural': 'Candidate Profiles'},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
