# Generated by Django 4.2.26 on 2025-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique candidate ID (e.g., JXCAN001)', max_length=20, null=True, unique=True),
        ),
    ]
