# Generated by Django 4.2.7 on 2025-11-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=20),
        ),
    ]
