# Generated by Django 4.2.7 on 2025-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_profiles/'),
        ),
    ]
