# Generated by Django 4.2.26 on 2025-11-28 09:16

from django.db import migrations


def generate_candidate_ids(apps, schema_editor):
    """Generate candidate IDs for existing candidates without IDs"""
    CandidateProfile = apps.get_model('users_app', 'CandidateProfile')
    
    # Get all candidates without a candidate_id
    candidates = CandidateProfile.objects.filter(candidate_id__isnull=True).order_by('id')
    
    for index, candidate in enumerate(candidates, start=1):
        candidate.candidate_id = f'JXCAN{index:03d}'
        candidate.save(update_fields=['candidate_id'])
    
    print(f"Generated {candidates.count()} candidate IDs")


def reverse_candidate_ids(apps, schema_editor):
    """Remove candidate IDs if migration is reversed"""
    CandidateProfile = apps.get_model('users_app', 'CandidateProfile')
    CandidateProfile.objects.all().update(candidate_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_candidateprofile_candidate_id'),
    ]

    operations = [
        migrations.RunPython(generate_candidate_ids, reverse_candidate_ids),
    ]
